#tribits_package_define_dependencies(
#  LIB_REQUIRED_TPLS  HeaderOnlyTpl
#  LIB_OPTIONAL_TPLS  SimpleTpl  MPI
#  REGRESSION_EMAIL_LIST simplecxx-regressions@someurl.none
#  )


  SET(LIB_REQUIRED_DEP_PACKAGES)
  SET(LIB_OPTIONAL_DEP_PACKAGES)
  SET(TEST_REQUIRED_DEP_PACKAGES)
  SET(TEST_OPTIONAL_DEP_PACKAGES)
  SET(LIB_REQUIRED_DEP_TPLS MPI Trilinos)
  SET(LIB_OPTIONAL_DEP_TPLS)
  SET(TEST_REQUIRED_DEP_TPLS)
  SET(TEST_OPTIONAL_DEP_TPLS)
